import { Metadata } from 'next';
import { FileJson, Users, MessageSquare } from 'lucide-react';
import { ShowcaseClient } from './ShowcaseClient';
import sessionsData from '@/lib/featured-sessions.json';

export const metadata: Metadata = {
    title: 'Showcase - ChaosLM',
    description: 'Explore featured discussion sessions and replays.',
};

async function getFeaturedSessions() {
    // Use statically generated JSON data (works on Cloudflare)
    return sessionsData || [];
}

export default async function ShowcasePage() {
    const sessions = await getFeaturedSessions();

    return (
        <div className="min-h-screen bg-zinc-50 dark:bg-black text-zinc-900 dark:text-zinc-50 pt-20 px-4 sm:px-6 lg:px-8 pb-12">
            <div className="max-w-7xl mx-auto">
                <header className="mb-10 text-center">
                    <h1 className="text-4xl font-black text-zinc-900 dark:text-zinc-100 mb-4">
                        Discussion Showcase
                    </h1>
                    <p className="text-zinc-600 dark:text-zinc-400 max-w-2xl mx-auto text-lg">
                        Explore a collection of curated ChaosLM sessions. Replay fascinating debates, chaotic arguments, and insightful conversations generated by AI agents.
                    </p>
                </header>

                {sessions.length === 0 ? (
                    <div className="text-center py-20 border-2 border-dashed border-zinc-200 dark:border-zinc-800 rounded-3xl bg-white/50 dark:bg-zinc-900/50">
                        <div className="inline-flex p-4 rounded-full bg-zinc-100 dark:bg-zinc-800 mb-4">
                            <FileJson className="w-8 h-8 text-zinc-400" />
                        </div>
                        <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">No Featured Sessions Yet</h3>
                        <p className="text-zinc-500 mt-2 max-w-md mx-auto">
                            The showcase is empty. Add JSON session files to <code>/public/featured-sessions</code> to see them here.
                        </p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {sessions.map((session: any) => ( // eslint-disable-line @typescript-eslint/no-explicit-any
                            <div key={session.filename} className="group relative bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl overflow-hidden hover:shadow-xl hover:shadow-zinc-500/10 hover:border-zinc-400 dark:hover:border-zinc-600 transition-all duration-300 flex flex-col">
                                <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-100 transition-opacity">
                                    <FileJson className="w-24 h-24 text-zinc-900 dark:text-white transform rotate-12 translate-x-8 -translate-y-8" />
                                </div>

                                <div className="p-6 flex-1 flex flex-col relative z-10">
                                    <div className="flex items-center gap-2 mb-4">
                                        <span className="px-2.5 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300">
                                            {session.mode}
                                        </span>
                                        <span className="text-xs text-zinc-400 font-mono">
                                            {new Date(session.timestamp).toLocaleDateString()}
                                        </span>
                                    </div>

                                    <h3 className="text-xl font-bold mb-3 line-clamp-2 group-hover:text-zinc-600 dark:group-hover:text-zinc-300 transition-colors">
                                        {session.topic}
                                    </h3>

                                    <div className="flex items-center gap-4 text-sm text-zinc-500 dark:text-zinc-400 mt-auto pt-4 border-t border-zinc-100 dark:border-zinc-800/50">
                                        <div className="flex items-center gap-1.5">
                                            <Users className="w-4 h-4" />
                                            <span>{session.agentsCount} Agents</span>
                                        </div>
                                        <div className="flex items-center gap-1.5">
                                            <MessageSquare className="w-4 h-4" />
                                            <span>{session.turnsCount} Turns</span>
                                        </div>
                                    </div>
                                </div>

                                <div className="p-4 bg-zinc-50 dark:bg-zinc-950/50 border-t border-zinc-200 dark:border-zinc-800 flex items-center justify-between">
                                    <div className="text-xs text-zinc-400 truncate max-w-[150px]" title={session.filename}>
                                        {session.filename}
                                    </div>
                                    <ShowcaseClient sessionData={session.data} />
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}
